name: Deploy with ARM

on:
  push:
    branches: [ main ] # Triggers the workflow on push on the main branch
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab



jobs:

  deploy_ARM:
   

  build_and_deploy_function_app:
   
